### ISSUE TITLE
Could not find a valid gem 'docraptor-cli'

### ISSUE THREAD

**Issue by asemahle** [DocRaptor/docraptor-cli#1]
Hi, when I run the installation command

``` bash
gem install docraptor-cli
```

I get the errors

``` bash
ERROR:  Could not find a valid gem 'docraptor-cli' (>= 0) in any repository
ERROR:  Possible alternatives: doc_raptor, docraptor, domainr-cli, octocli
```

I'm running ruby 2.3.0p0 [x64-mingw32] with gem 2.5.1

**Comment by janxious** [comment]
Yeah, making the gemspec so that the docraptor command gets put into your path is still on the TODOs, after inspecting the current state of the repo. The instructions for installation _right now_ probably could be:
- `git clone git@github.com:DocRaptor/docraptor-cli.git && cd docraptor-cli`
- `bundle install`
- `bin/docraptor <some options>`

**Comment by asemahle** [comment]
The installation instructions seem to have worked. Specifically, I added `source "https://rubygems.org"` to the gemfile (so that gem dependencies are automatically downloaded) and then

``` bash
git clone git@github.com:DocRaptor/docraptor-cli.git && cd docraptor-cli
gem install bundler
bundle install
```

This seemed to work... My `C:\Ruby23-x64\lib\ruby\gems\2.3.0\gems` folder now contains `docraptor-0.2.0`. But I can't run the gem. Even in `docraptor-cli\bin`, all I get is 

`'docraptor' is not recognized as an internal or external command, operable program or batch file.`

I'm not familiar with the process for building gems. Does something need to be changed for it to work on a Windows OS?

**Comment by jqr** [comment]
Apologies, this is my fault for stepping away before releasing the actual gem. I'll release it shortly and things should be a bit simpler.

**Comment by jqr** [comment]
@asemahle, you need to execute `bundle exec docraptor` to reference the binary, or tell bundler to make [binstubs in your project](http://bundler.io/v1.11/bundle_binstubs.html) and then you can just use `bin/docraptor` from within your project.

**Comment by jqr** [comment]
The gem is [now released](https://rubygems.org/gems/docraptor-cli), you'll want `0.0.2` because I forgot to include the binary in `0.0.1`, oops.
